config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  resources :homes, :about, :posts
  get "posts" => "posts#search", as: :post_search

  resources :posts do
    resources :comments, only: [:new, :create, :update, :destroy]
  end

  resources :users, only: [:new, :create, :edit, :update]
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :posts do
    resources :favourites, only: [:create, :destroy]
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :title, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates :body, presence: true,
                   uniqueness: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]
  
  belongs_to :user
  has_many :comments, dependent: :destroy

# For favourite_post index
  has_many :favourites, dependent: :destroy
  has_many :favourited_users, through: :favourites, source: :user

  validates :title, presence: true,
                    uniqueness: true

# For searching
  def self.search(term)
    wildcard_term = "%#{term}%"
    where("title ILIKE :term OR body ILIKE :term", {term: wildcard_term})
  end

  def favourite_for(user)
    favourites.find_by_user_id(user)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessor :password
  # attr_accessor :password_confirmation
  has_many :posts
  has_many :comments

  has_many :favourites, dependent: :destroy
  has_many :favourited_posts, through: :favourites, source: :posts
  validates :first_name, uniqueness: true, presence: true

  has_secure_password
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_user!
    redirect_to new_session_path, notice: "Please sign in" unless user_signed_in?
  end

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  def current_user
    @user ||= User.find_by_id session[:user_id]
  end
  helper_method :current_user

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    find_posts
    comments_params = params.require(:comment).permit(:body,:post_id,:user_id)
    @comment = Comment.new comments_params
    @comment.post_id = @post.id
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.html {redirect_to post_path(@post)}
        format.js {render :create_success}
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    respond_to do |format|
      if current_user.id == @comment.user_id
        find_posts
        @comment.destroy
        format.html {redirect_to post_path(@post)}
        format.js {render}
      else
        format.html {redirect_to root_path, notice: "Unathorized!!!!"}
      end
    end
  end

  private

  def find_posts
    @post = Post.friendly.find(params[:post_id])
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def create
    @favourite = Favourite.new
    @favourite.user_id = current_user.id
    find_posts
    @favourite.post_id = @post.id
    respond_to do |format|
      if @favourite.save
        format.html {redirect_to post_path(@post), alert: "Added to favourite"}
        format.js {render :create_success}
      else
        format.html {redirect_to post_path(@post), alert: "Cant be added to favourite"}
      end
    end
  end

  def destroy
    find_posts
    @favourite = @post.favourites.find_by_user_id current_user
    @favourite.destroy
    respond_to do |format|
      format.html {redirect_to post_path(@post), alert: "Removed from the favourite list"}
      format.js {render}
    end
  end

  private

  def find_posts
    @post = Post.friendly.find(params[:post_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @user = current_user
  end

  def show
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    post_params = params.require(:post).permit(:title,:body)
    @post = Post.new post_params
    if @post.save
      redirect_to homes_path
    else
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new,:create,:edit]
  before_action :find_post, only: [:show,:edit,:update,:destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    post_params = params.require(:post).permit([:title, :body, :category, :user_id])
    @post = Post.new post_params
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
    @comments = Comment.new
    @favourite = @post.favourite_for(current_user)
  end

  def edit
  end

  def update
    @post.slug = nil
    if current_user == @post.user
      post_params = params.require(:post).permit(:title,:body)
      if @post.update post_params
        redirect_to post_path(@post)
      else
        render :edit
        end
    else
        redirect_to root_path, notice: "Get the fuck out Tom"
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  def search
    @posts = Post.search(params[:p])
    render :index
  end

  private

  def find_post
    @post = Post.friendly.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email params[:email]
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Logged in"
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Signed out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:first_name,:last_name,:email,:password,:password_confirmation)
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Logged In"
    else
      render :new
    end
  end

  def edit
    if current_user != nil && @user.id == session[:user_id]
      @user = User.find(params[:id])
    else
      redirect_to root_path
    end
  end

  def update
    user_params = params.require(:user).permit(:first_name,:last_name,:email,:password,:password_confirmation)
    @user = User.find(params[:id])
    if @user.update user_params
    redirect_to root_path, notice: "Updated"
    else
      render :edit
    end
  end

  def change_password
    
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_show.html.erb
<div id="<%= dom_id(f) %>">
  <li class="list-group-item">
    <%= f.body %>
    <br>
    <%= "Commented By: " + f.user.first_name %>
    <% if user_signed_in? && f.user_id? && current_user.id == f.user_id%>
      <br>
      <%= link_to "Delete", post_comment_path(@post.id, f.id), method: :delete ,remote: true  %>
    <% end %>
  </li>
</div>

app/views/comments/create_success.js.erb
$(".comments").prepend("<%= j(render('show', {f: @comment})) %>");

app/views/comments/destroy.js.erb
$("#<%= dom_id(@comment) %>").fadeOut(1000, function(){ $(this).remove(); });

app/views/favourites/_form.html.erb
<% @favourite = @post.favourites.find_by_user_id current_user %>
<% if current_user != @post.user_id %>
  <% if @favourite %>
    <%= link_to icon('heart', font: { size: '2em' }), post_favourite_path(@post,@favourite), method: :delete, remote: true %>
  <% else %>
    <%= link_to icon('heart-o'), post_favourites_path(@post), method: :POST, remote: true %>
  <% end %>
<% end %>

app/views/favourites/create_failure.js.erb
$(".favourite").html("<%= j render 'form' %>");

app/views/favourites/create_success.js.erb
$(".favourite").html("<%= j render 'form' %>");

app/views/favourites/destroy.js.erb
$(".favourite").html("<%= j render 'form' %>");

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<% @post.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>

<%= simple_form_for @post do |f| %>
  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.button :submit, class:"btn btn-primary" %>
<% end %>



<!-- <%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit %>
<% end %> -->

app/views/posts/index.html.erb
<h1>All Posts</h1>

<%= form_tag(post_search_path, method: "get") do %>
  <%= label_tag(:p, "Search for:") %>
  <%= text_field_tag :p, params[:p] %>
  <%= submit_tag("Search") %>
<% end %>

<% @posts.each do |post| %>
  <ul>
    <li><%=link_to post.title, post_path(post) %></li>
    <!-- <li><%= post.body %></li> -->
  </ul>
<% end %>

app/views/posts/new.html.erb
<h1>New Posts</h1>

<% @post.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>


<%= simple_form_for @post do |f| %>
  <%= f.input :title, placeholder: "Let's talk buddy..."%>
  <%= f.input :body, hint: "Whatever you want write it here.." %>
  <%= f.input :category, priority: ["Coding"], collection: ["Science","Food","Sports","Books","Coding"] %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>


<!-- Regular form_for -->
<!-- <%= form_for @post do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <%= f.select(:category) do %>
    <% [['Science', 'Science'], ['Food', 'Food'], ['Sports', 'Sports'],['Books','Books']].each do |c| -%>
      <%= content_tag(:option, c.first, value: c.last) %>
    <% end %>
  <% end %>
  <div>
    <%= f.submit %>
  </div>
<% end %> -->

app/views/posts/search.html.erb
<h1>Search</h1>
<%= @posts %>

app/views/posts/show.html.erb
<h1>Post</h1>

<%= @post.title %>
<hr>
<%= @post.body %>
<hr>
<%= "Category: " + @post.category %>
<!-- Display the user  -->
<% if @post.user != nil %>
  <hr>
  <%= "Created By: " + @post.user.first_name %>
  <hr>
<% end %>

<!-- Favourting if the user is not the owner of the post -->
<!-- <% if current_user != @post.user_id %>
  <%= link_to icon('thumbs-o-up'), post_favourites_path(@post), method: :POST, remote: true %>
  <% if @favourite %>
    <%= link_to icon('thumbs-o-down'), post_favourite_path(@post,@favourite), method: :delete, data: {confirm: "Are you sure?"}, remote: true %>
  <% end %>
<% end %> -->
<div class="favourite">
  <%= render "/favourites/form" %>
</div>

<!-- Checking to see if User is authorized to edit or delete -->
<div>
  <% if user_signed_in? && current_user.id == @post.user_id %>
    <%= link_to "Edit", edit_post_path(params[:id]) %>
    <%= link_to "Delete", post_path, method: :delete, data: {confirm: "Are you sure?"} %>
  <% end %>
</div>

<%= simple_form_for [@post, @comments] do |f|%>
<%= f.input :body %>
<%= f.button :submit, class: "btn btn-primary" %>
<% end %>
<!-- Form for comments -->
<!-- <div>
  <%= form_for [@post, @comments], remote: true do |f| %>
    <%= f.text_area :body %>
    <%= f.submit %>
  <% end %>
</div> -->

  <!-- Display Comments -->
  <div class="comments">
  <ul class="list-group">
  <% @post.comments.each do |f| %>
    <%= render "/comments/show", f: f  %>
  <% end %>
  </ul>
</div>

app/views/users/edit.html.erb
<h1>Edit User info</h1>

<%= @user.errors.full_messages.join(", ") %>

<%= form_for @user do |f| %>
<div>
  <%= f.label :first_name  %>
  <%= f.text_field :first_name %>
</div>

<div>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
</div>

<div>
  <%= f.label :email %>
  <%= f.text_field :email %>
</div>

<div>
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>

<div>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</div>

<%= f.submit %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= @user.errors.full_messages.join(", ") %>
<%= form_for @user do |f| %>
<div>
  <%= f.label :first_name  %>
  <%= f.text_field :first_name %>
</div>

<div>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
</div>

<div>
  <%= f.label :email %>
  <%= f.text_field :email %>
</div>

<div>
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>

<div>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</div>

<%= f.submit %>
<% end %>